version: '3'
services:
  app:
    image: streamlit-pyvista
    build: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app  # This mounts the local frontend directory to the container's /app directory
